[package]
name = "rusty-crud-server"
version = "0.5.3"
edition = "2024"

[dependencies]
rusty = { path = "../rusty" }
axum.workspace = true
diesel.workspace = true
deadpool-diesel.workspace = true
tokio.workspace = true

[lints]
workspace = true
