[package]
name = "rusty-crud-client"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
rusty = { path = "../rusty" }
reqwest.workspace = true
tokio.workspace = true

[lints]
workspace = true
