[package]
name = "rusty"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
diesel.workspace = true
reqwest.workspace = true
serde.workspace = true

[lints]
workspace = true
