[package]
name = "rusty-migration"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
diesel.workspace = true
diesel_migrations.workspace = true

[lints]
workspace = true
