[package]
name = "rusty-game-client"
version = "0.5.1"
edition = "2024"

[dependencies]
rusty = { path = "../rusty" }
clap.workspace = true
reqwest.workspace = true
tokio.workspace = true

[lints]
workspace = true
