[package]
name = "rusty-game-client"
version = "0.5.3"
edition = "2024"

[dependencies]
rusty = { path = "../rusty" }
clap.workspace = true
clap_complete.workspace = true
reqwest.workspace = true
serde_json.workspace = true
tokio.workspace = true

[lints]
workspace = true
