name: Nightly Container Build

on:
  workflow_dispatch:
  schedule:
    - cron: '42 23 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        container:
          - crud-server
          - game-server
          - migration
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      - name: Set up QEMU
        uses: docker/setup-qemu-action@29109295f81e9208d7d86ff1c6c12d2833863392 # v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push ${{ matrix.container }}
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6
        with:
          context: .
          file: Containerfile
          target: runtime-${{ matrix.container }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/alisterd51/rusty-${{ matrix.container }}:latest
            ghcr.io/alisterd51/rusty-${{ matrix.container }}:nightly
