name: Container CI

on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string

env:
  ARCHITECTURES: amd64 arm64

jobs:
  container-build:
    strategy:
      fail-fast: false
      matrix:
        container:
          - crud-server
          - game-server
          - game-frontend
          - migration
          - rauthy-init
        arch:
          - amd64
          - arm64
        include:
          - arch: amd64
            runner: ubuntu-24.04
          - arch: arm64
            runner: ubuntu-24.04-arm
    runs-on: ${{ matrix.runner }}
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd # v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Login to dhi.io
        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4
        with:
          registry: dhi.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push ${{ matrix.container }} (${{ matrix.arch }})
        uses: docker/build-push-action@bcafcacb16a39f128d818304e6c9c0c18556b85f # v7
        with:
          context: .
          file: Containerfile
          target: runtime-${{ matrix.container }}
          platforms: linux/${{ matrix.arch }}
          push: true
          tags: |
            ghcr.io/alisterd51/rusty-${{ matrix.container }}:${{ inputs.tag }}-${{ matrix.arch }}

  container-manifest:
    needs: container-build
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        container:
          - crud-server
          - game-server
          - game-frontend
          - migration
          - rauthy-init
    permissions:
      contents: read
      packages: write
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd # v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Create and push manifest
        env:
          CONTAINER_NAME: ${{ matrix.container }}
          IMAGE_TAG: ${{ inputs.tag }}
        run: |
          IMAGES=()
          IFS=' ' read -r -a ARCH_ARRAY <<< "$ARCHITECTURES"
          for arch in "${ARCH_ARRAY[@]}"; do
            IMAGES+=("ghcr.io/alisterd51/rusty-${CONTAINER_NAME}:${IMAGE_TAG}-$arch")
          done
          docker buildx imagetools create -t ghcr.io/alisterd51/rusty-${CONTAINER_NAME}:${IMAGE_TAG} "${IMAGES[@]}"
          docker buildx imagetools create -t ghcr.io/alisterd51/rusty-${CONTAINER_NAME}:latest "${IMAGES[@]}"
