name: Nightly

on:
  workflow_dispatch:
  schedule:
    - cron: '42 23 * * *'

jobs:
  prerelease:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: install deps
        run: |
          sudo apt-get update && sudo apt-get install -y protobuf-compiler libprotobuf-dev musl-tools
      - name: Install musl target
        run: rustup target add x86_64-unknown-linux-musl
      - name: Build clients
        run: |
          cargo build --release --target x86_64-unknown-linux-musl -p crud-client -p game-client
      - name: Build servers
        run: |
          cargo build --release -p crud-server -p game-server -p migration
      - name: Create nightly tag
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/nightly',
              sha: context.sha
            }).catch(err => {
              if (err.status !== 422) throw err;
              github.rest.git.updateRef({
                owner: context.repo.owner,
                repo: context.repo.repo,
                ref: 'tags/nightly',
                sha: context.sha
              });
            })
      - name: Release
        uses: softprops/action-gh-release@3bb12739c298aeb8a4eeaf626c5b8d85266b0e65 # v2
        with:
          files: |
            target/x86_64-unknown-linux-musl/release/crud-client
            target/x86_64-unknown-linux-musl/release/game-client
            target/release/crud-server
            target/release/game-server
            target/release/migration
            target/release/rauthy-init
          prerelease: true
          name: nightly
          tag_name: nightly

  container-build:
    uses: ./.github/workflows/container-ci.yaml
    permissions:
      contents: read
      packages: write
    with:
      tag: nightly
    secrets: inherit
