name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: install deps
        run: |
          sudo apt-get update && sudo apt-get install -y protobuf-compiler libprotobuf-dev musl-tools
      - name: Install musl target
        run: rustup target add x86_64-unknown-linux-musl
      - name: Build clients
        run: |
          cargo build --release --target x86_64-unknown-linux-musl -p crud-client -p game-client
      - name: Build servers
        run: |
          cargo build --release -p crud-server -p game-server -p migration -p rauthy-init
      - name: Release
        uses: softprops/action-gh-release@3d0d9888cb7fd7b750713d6e236d1fcb99157228 # v3
        with:
          generate_release_notes: true
          files: |
            target/x86_64-unknown-linux-musl/release/crud-client
            target/x86_64-unknown-linux-musl/release/game-client
            target/release/crud-server
            target/release/game-server
            target/release/migration
            target/release/rauthy-init

  container-build:
    uses: ./.github/workflows/container-ci.yaml
    permissions:
      contents: read
      packages: write
    with:
      tag: ${{ github.ref_name }}
    secrets: inherit
